version: '3'
services:
  couchbase:
    build: .
    ports:
      - "8091:8091"  # Порт администратора
      - "8092:8092"  # Порт кластера
      - "8093:8093"  # Порт GSI
      - "8094:8094"  # Порт FT
      - "11207:11207" # Порт управления
      - "11210:11210" # Порт кластера
      - "11211:11211" # Порт кластера
    environment:
      - CB_REST_USERNAME=admin
      - CB_REST_PASSWORD=password
